### ISSUE TITLE
Dataobjects with TREE signatures not read correctly

### ISSUE THREAD

**Issue by synaptic** [jjhelmus/pyfive#3]
I have an HDF5 file that has multiple groups in parallel under a parent group.  When I try to read it with `pyfive`, it complains when trying to get the parent group.  The stack trace is the following:

``` python
gp = grand_parent_gp['parent_name']

Traceback (most recent call last):
  File ...
    gp = grand_parent_gp['parent_name']
  File "...\pyfive\high_level.py", line 59, in __getitem__
    return Group(self.name + sep + y, dataobjects, self)
  File "...\pyfive\high_level.py", line 35, in __init__
    self._links = dataobjects.get_links()
  File "...\pyfive\low_level.py", line 515, in get_links
    return self._get_links_from_symbol_tables(sym_tbl_msgs)
  File "...\pyfive\low_level.py", line 531, in _get_links_from_symbol_tables
    table = SymbolTable(self.fh, symbol_table_address)
  File "...\pyfive\low_level.py", line 209, in __init__
    assert node['signature'] == b'SNOD'
AssertionError
```
It appears that the signature for that node is `b'TREE` which is not supported.  How to fix?

**Comment by jjhelmus** [comment]
@synaptic Thanks for reporting this.  It seems as if the logic that pyfive is using for finding groups/datasets does not work when there are a large number of groups/datasets.  A simple example which reproduces this bug is:

``` python
# create a HDF5 file with a large number of sub-groups
import h5py
f = h5py.File('many_groups.h5', 'w')
grp = f.create_group("bar")
for i in range(200):
    grp.create_group('group_%i' % (i))
f.close()

# Try to read the file produced
import pyfive
f = pyfive.File('many_groups.h5')
grp = f['bar']
```

This cause of this issue is that pyfive assumes that version 1 B-Trees contain only a single leaf node which is not true when the number of entries in the tree is larger than can fit in a single node, [see low_level.py lines 59-90]( https://github.com/jjhelmus/pyfive/blob/16211c8535176b3e4d91358adab7c227952df11d/pyfive/low_level.py#L59-L90).  Logic will need to be added to traverse the tree and load data from all the leaf nodes as is done in the [**BTreeRawDataChunks** class](https://github.com/jjhelmus/pyfive/blob/16211c8535176b3e4d91358adab7c227952df11d/pyfive/low_level.py#L93-L120). I'll look at adding this logic when I have time to work on pyfive.

**Comment by synaptic** [comment]
I made changes based on a comment from [this documentation](https://www.hdfgroup.org/HDF5/doc/H5.format.html): "One implementation of a group is a collection of symbol table nodes indexed by a B-tree."   So by simply checking whether the symbol table node is a 'TREE' and looping it as a sub-tree, I was successful in loading all of my groups.

**Comment by synaptic** [comment]
Thanks for the clarification.  I did think what I wrote seemed too easy!  I downloaded your latest commit and can confirm it works with files with hundreds of groups.  Great job!
